export const SIGNUP_START = "SIGNUP_START"
export const SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL"
export const SIGNUP_FAILED = "SIGNUP_FAILED"

export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const GET_RECIPE_START = "GET_RECIPE_START"
export const GET_RECIPE_SUCCESSFUL = "GET_RECIPE_SUCCESSFUL"
export const GET_RECIPE_FAILED = "GET_RECIPE_FAILED"

export const GET_RECIPES_START = "GET_RECIPES_START"
export const GET_RECIPES_SUCCESSFUL = "GET_RECIPES_SUCCESSFUL"
export const GET_RECIPES_FAILED = "GET_RECIPES_FAILED"

export const CREATE_RECIPE_START = "CREATE_RECIPE_START"
export const CREATE_RECIPE_SUCCESSFUL = "CREATE_RECIPE_SUCCESSFUL"
export const CREATE_RECIPE_FAILED = "CREATE_RECIPE_FAILED"